// <auto-generated />
using System;
using Biob.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biob.Data.Data.Migrations
{
    [DbContext(typeof(BiobDataContext))]
    [Migration("20181120100827_AddedModelsAndSeedData")]
    partial class AddedModelsAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Biob.Data.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenreName")
                        .IsRequired();

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new { GenreId = new Guid("8068cbf6-c595-4733-9c24-8104e8454b4c"), GenreName = "Horror" },
                        new { GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70"), GenreName = "Drama" },
                        new { GenreId = new Guid("01c66e3e-8c25-4f5c-a2c5-512c79d09aa6"), GenreName = "Comedy" },
                        new { GenreId = new Guid("976a7a24-1c25-4a7f-97c6-1a019c5c148d"), GenreName = "Romance" },
                        new { GenreId = new Guid("72163c34-3d32-4a78-9701-1f708053978f"), GenreName = "Action" },
                        new { GenreId = new Guid("e143ebff-a0bd-4107-889f-9bff26eda916"), GenreName = "Fiction" },
                        new { GenreId = new Guid("0532f0df-c92d-4a10-9d1a-8a5935c541a2"), GenreName = "Biography" },
                        new { GenreId = new Guid("e48aa8e0-3efc-4acd-a0d5-88c82551807a"), GenreName = "Fantasy" },
                        new { GenreId = new Guid("76c2fab8-7161-49b7-88c6-f3aaf484ea64"), GenreName = "Family" }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.Hall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HallNo");

                    b.Property<int>("NoOfSeats");

                    b.Property<bool>("ThreeDee")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("HallId");

                    b.ToTable("Halls");

                    b.HasData(
                        new { HallId = 1, HallNo = 1, NoOfSeats = 10, ThreeDee = true },
                        new { HallId = 2, HallNo = 2, NoOfSeats = 20, ThreeDee = false },
                        new { HallId = 3, HallNo = 3, NoOfSeats = 20, ThreeDee = false }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.HallSeat", b =>
                {
                    b.Property<int>("HallId");

                    b.Property<int>("SeatId");

                    b.Property<int>("HallSeatId");

                    b.HasKey("HallId", "SeatId");

                    b.HasAlternateKey("HallSeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("HallSeats");

                    b.HasData(
                        new { HallId = 1, SeatId = 1, HallSeatId = 1 },
                        new { HallId = 1, SeatId = 2, HallSeatId = 2 },
                        new { HallId = 1, SeatId = 3, HallSeatId = 3 },
                        new { HallId = 1, SeatId = 4, HallSeatId = 4 },
                        new { HallId = 1, SeatId = 5, HallSeatId = 5 },
                        new { HallId = 1, SeatId = 11, HallSeatId = 6 },
                        new { HallId = 1, SeatId = 12, HallSeatId = 7 },
                        new { HallId = 1, SeatId = 13, HallSeatId = 8 },
                        new { HallId = 1, SeatId = 14, HallSeatId = 9 },
                        new { HallId = 1, SeatId = 15, HallSeatId = 10 },
                        new { HallId = 2, SeatId = 1, HallSeatId = 11 },
                        new { HallId = 2, SeatId = 2, HallSeatId = 12 },
                        new { HallId = 2, SeatId = 3, HallSeatId = 13 },
                        new { HallId = 2, SeatId = 4, HallSeatId = 14 },
                        new { HallId = 2, SeatId = 5, HallSeatId = 15 },
                        new { HallId = 2, SeatId = 6, HallSeatId = 16 },
                        new { HallId = 2, SeatId = 7, HallSeatId = 17 },
                        new { HallId = 2, SeatId = 8, HallSeatId = 18 },
                        new { HallId = 2, SeatId = 9, HallSeatId = 19 },
                        new { HallId = 2, SeatId = 10, HallSeatId = 20 },
                        new { HallId = 2, SeatId = 11, HallSeatId = 21 },
                        new { HallId = 2, SeatId = 12, HallSeatId = 22 },
                        new { HallId = 2, SeatId = 13, HallSeatId = 23 },
                        new { HallId = 2, SeatId = 14, HallSeatId = 24 },
                        new { HallId = 2, SeatId = 15, HallSeatId = 25 },
                        new { HallId = 2, SeatId = 16, HallSeatId = 26 },
                        new { HallId = 2, SeatId = 17, HallSeatId = 27 },
                        new { HallId = 2, SeatId = 18, HallSeatId = 28 },
                        new { HallId = 2, SeatId = 19, HallSeatId = 29 },
                        new { HallId = 2, SeatId = 20, HallSeatId = 30 },
                        new { HallId = 3, SeatId = 1, HallSeatId = 31 },
                        new { HallId = 3, SeatId = 2, HallSeatId = 32 },
                        new { HallId = 3, SeatId = 3, HallSeatId = 33 },
                        new { HallId = 3, SeatId = 4, HallSeatId = 34 },
                        new { HallId = 3, SeatId = 5, HallSeatId = 35 },
                        new { HallId = 3, SeatId = 6, HallSeatId = 36 },
                        new { HallId = 3, SeatId = 7, HallSeatId = 37 },
                        new { HallId = 3, SeatId = 8, HallSeatId = 38 },
                        new { HallId = 3, SeatId = 9, HallSeatId = 39 },
                        new { HallId = 3, SeatId = 10, HallSeatId = 40 },
                        new { HallId = 3, SeatId = 11, HallSeatId = 41 },
                        new { HallId = 3, SeatId = 12, HallSeatId = 42 },
                        new { HallId = 3, SeatId = 13, HallSeatId = 43 },
                        new { HallId = 3, SeatId = 14, HallSeatId = 44 },
                        new { HallId = 3, SeatId = 15, HallSeatId = 45 },
                        new { HallId = 3, SeatId = 16, HallSeatId = 46 },
                        new { HallId = 3, SeatId = 17, HallSeatId = 47 },
                        new { HallId = 3, SeatId = 18, HallSeatId = 48 },
                        new { HallId = 3, SeatId = 19, HallSeatId = 49 },
                        new { HallId = 3, SeatId = 20, HallSeatId = 50 }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Actors");

                    b.Property<int>("AgeRestriction");

                    b.Property<string>("Description")
                        .HasMaxLength(5000);

                    b.Property<int>("LengthInSeconds");

                    b.Property<string>("Poster");

                    b.Property<string>("Producer")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset>("Released");

                    b.Property<bool>("ThreeDee");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new { Id = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), Actors = "Christopher Nolan", AgeRestriction = 16, Description = "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.", LengthInSeconds = 9120, Poster = "", Producer = "Kevin De La Noy", Released = new DateTimeOffset(new DateTime(2005, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), ThreeDee = false, Title = "The Dark Knight" },
                        new { Id = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), Actors = "Balen, Jason, Mikkel", AgeRestriction = 16, Description = "Nightmare on earth where students fight to survive on a daily basis.", LengthInSeconds = 5400, Poster = "", Producer = "Jan Eg", Released = new DateTimeOffset(new DateTime(2016, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), ThreeDee = false, Title = "SKP" },
                        new { Id = new Guid("de9b842d-531a-4f17-ad69-0d3e11cb911d"), Actors = "Daniel Radcliffe, Emma Watson, Rupert Grint", AgeRestriction = 11, Description = "Albus Dumbledore, Minerva McGonagall, and Rubeus Hagrid, professors of Hogwarts School of Witchcraft and Wizardry, deliver a recently orphaned infant named Harry Potter to his only remaining relatives, the Dursleys.", LengthInSeconds = 9120, Poster = "", Producer = "David Heyman", Released = new DateTimeOffset(new DateTime(2001, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), ThreeDee = true, Title = "Harry Potter and the Sorcerer's Stone" },
                        new { Id = new Guid("195c5a46-96f9-446b-b4f7-864ab2dc49de"), Actors = "Rami Malek, Lucy Boynton, Joseph Mazzello", AgeRestriction = 11, Description = "A chronicle of the years leading up to Queen's legendary appearance at the Live Aid (1985) concert.", LengthInSeconds = 8040, Poster = "", Producer = "Bryan Singer", Released = new DateTimeOffset(new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), ThreeDee = false, Title = "Bohemian Rhapsody" },
                        new { Id = new Guid("174fd8d4-f72b-4059-a7ea-05e687026b0d"), Actors = "Tom Hardy, Michelle Williams, Riz Ahmed", AgeRestriction = 18, Description = "When Eddie Brock acquires the powers of a symbiote, he will have to release his alter-ego 'Venom' to save his life.", LengthInSeconds = 6720, Poster = "", Producer = "Ruben Fleischer", Released = new DateTimeOffset(new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), ThreeDee = true, Title = "Venom" },
                        new { Id = new Guid("163c03b3-a057-426d-afa3-1a2631a693e2"), Actors = "Lady Gaga, Bradley Cooper, Sam Elliott", AgeRestriction = 16, Description = "A musician helps a young singer find fame, even as age and alcoholism send his own career into a downward spiral.", LengthInSeconds = 8160, Poster = "", Producer = "Bradley Cooper", Released = new DateTimeOffset(new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)), ThreeDee = false, Title = "A Star Is Born" }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId");

                    b.Property<Guid>("GenreId");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new { MovieId = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70") },
                        new { MovieId = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), GenreId = new Guid("72163c34-3d32-4a78-9701-1f708053978f") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("8068cbf6-c595-4733-9c24-8104e8454b4c") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("01c66e3e-8c25-4f5c-a2c5-512c79d09aa6") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("976a7a24-1c25-4a7f-97c6-1a019c5c148d") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("72163c34-3d32-4a78-9701-1f708053978f") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("e143ebff-a0bd-4107-889f-9bff26eda916") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("0532f0df-c92d-4a10-9d1a-8a5935c541a2") },
                        new { MovieId = new Guid("45c0c223-de18-4e6e-99ea-aed94e7469f1"), GenreId = new Guid("e48aa8e0-3efc-4acd-a0d5-88c82551807a") },
                        new { MovieId = new Guid("de9b842d-531a-4f17-ad69-0d3e11cb911d"), GenreId = new Guid("e48aa8e0-3efc-4acd-a0d5-88c82551807a") },
                        new { MovieId = new Guid("de9b842d-531a-4f17-ad69-0d3e11cb911d"), GenreId = new Guid("76c2fab8-7161-49b7-88c6-f3aaf484ea64") },
                        new { MovieId = new Guid("195c5a46-96f9-446b-b4f7-864ab2dc49de"), GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70") },
                        new { MovieId = new Guid("195c5a46-96f9-446b-b4f7-864ab2dc49de"), GenreId = new Guid("0532f0df-c92d-4a10-9d1a-8a5935c541a2") },
                        new { MovieId = new Guid("195c5a46-96f9-446b-b4f7-864ab2dc49de"), GenreId = new Guid("76c2fab8-7161-49b7-88c6-f3aaf484ea64") },
                        new { MovieId = new Guid("174fd8d4-f72b-4059-a7ea-05e687026b0d"), GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70") },
                        new { MovieId = new Guid("174fd8d4-f72b-4059-a7ea-05e687026b0d"), GenreId = new Guid("72163c34-3d32-4a78-9701-1f708053978f") },
                        new { MovieId = new Guid("174fd8d4-f72b-4059-a7ea-05e687026b0d"), GenreId = new Guid("e143ebff-a0bd-4107-889f-9bff26eda916") },
                        new { MovieId = new Guid("163c03b3-a057-426d-afa3-1a2631a693e2"), GenreId = new Guid("6e0a64bc-7a50-4a6c-9125-8ccf6e54bf70") },
                        new { MovieId = new Guid("163c03b3-a057-426d-afa3-1a2631a693e2"), GenreId = new Guid("01c66e3e-8c25-4f5c-a2c5-512c79d09aa6") },
                        new { MovieId = new Guid("163c03b3-a057-426d-afa3-1a2631a693e2"), GenreId = new Guid("976a7a24-1c25-4a7f-97c6-1a019c5c148d") },
                        new { MovieId = new Guid("163c03b3-a057-426d-afa3-1a2631a693e2"), GenreId = new Guid("76c2fab8-7161-49b7-88c6-f3aaf484ea64") }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RowNo");

                    b.Property<int>("SeatNo");

                    b.HasKey("SeatId");

                    b.ToTable("Seats");

                    b.HasData(
                        new { SeatId = 1, RowNo = 1, SeatNo = 1 },
                        new { SeatId = 2, RowNo = 1, SeatNo = 2 },
                        new { SeatId = 3, RowNo = 1, SeatNo = 3 },
                        new { SeatId = 4, RowNo = 1, SeatNo = 4 },
                        new { SeatId = 5, RowNo = 1, SeatNo = 5 },
                        new { SeatId = 6, RowNo = 1, SeatNo = 6 },
                        new { SeatId = 7, RowNo = 1, SeatNo = 7 },
                        new { SeatId = 8, RowNo = 1, SeatNo = 8 },
                        new { SeatId = 9, RowNo = 1, SeatNo = 9 },
                        new { SeatId = 10, RowNo = 1, SeatNo = 10 },
                        new { SeatId = 11, RowNo = 2, SeatNo = 1 },
                        new { SeatId = 12, RowNo = 2, SeatNo = 2 },
                        new { SeatId = 13, RowNo = 2, SeatNo = 3 },
                        new { SeatId = 14, RowNo = 2, SeatNo = 4 },
                        new { SeatId = 15, RowNo = 2, SeatNo = 5 },
                        new { SeatId = 16, RowNo = 2, SeatNo = 6 },
                        new { SeatId = 17, RowNo = 2, SeatNo = 7 },
                        new { SeatId = 18, RowNo = 2, SeatNo = 8 },
                        new { SeatId = 19, RowNo = 2, SeatNo = 9 },
                        new { SeatId = 20, RowNo = 2, SeatNo = 10 }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.Showtime", b =>
                {
                    b.Property<Guid>("ShowtimeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HallId");

                    b.Property<Guid>("MovieId");

                    b.Property<bool>("ThreeDee")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("TimeOfPlaying");

                    b.HasKey("ShowtimeId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new { ShowtimeId = new Guid("092ca7c5-ae83-4a52-a38b-cfc7c8e40e9a"), HallId = 1, MovieId = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), ThreeDee = false, TimeOfPlaying = new DateTimeOffset(new DateTime(2018, 12, 22, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)) },
                        new { ShowtimeId = new Guid("5e0d5ad3-22b0-4bdc-808c-62b8f50d0796"), HallId = 2, MovieId = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), ThreeDee = false, TimeOfPlaying = new DateTimeOffset(new DateTime(2018, 12, 23, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)) },
                        new { ShowtimeId = new Guid("cf3c5f8e-94ee-494a-b0f1-4a48d9d8291f"), HallId = 3, MovieId = new Guid("9d90a452-9547-4d04-98ed-7d617e64ae1e"), ThreeDee = false, TimeOfPlaying = new DateTimeOffset(new DateTime(2018, 12, 24, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)) }
                    );
                });

            modelBuilder.Entity("Biob.Data.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<int>("HallSeatId");

                    b.Property<bool>("Paid");

                    b.Property<int>("Price");

                    b.Property<bool>("Reserved");

                    b.Property<Guid>("ShowtimeId");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Biob.Data.Models.HallSeat", b =>
                {
                    b.HasOne("Biob.Data.Models.Hall", "Hall")
                        .WithMany("HallSeats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Biob.Data.Models.Seat", "Seat")
                        .WithMany("HallSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Biob.Data.Models.MovieGenre", b =>
                {
                    b.HasOne("Biob.Data.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Biob.Data.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
